//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSourceControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firearms
    {
        public int FirearmID { get; set; }
        public string SerialNumber { get; set; }
        public string Manufacturer { get; set; }
        public string ModelName { get; set; }
        public string Caliber { get; set; }
        public decimal Price { get; set; }
    }
}
